### ISSUE TITLE
疑问：关于路线规划等问题

### ISSUE THREAD

**Issue by fatinghenji** [Starry-Wind/Honkai-Star-Rail#1]
**非常感谢脚本！！！解放了！！！！但有一点点的问题想请教下：**
1. 如果部分舱门没有打开是否会影响脚本运行？有哪些舱门是需要必须打开的？
2. 如果在使用脚本前手动清理了部分怪物是否会出现脚本运行错误的情况？
3. 部分怪物为巡视怪，怎么确定一定会碰得到呢？

**Comment by Starry-Wind** [comment]
1：传送点建议全开启，地图也建议探索一遍开开机关，路线是从b站视频找的，建议先跑一次图看看有没有机关需要打开之类的,避免有舱门打不开情况（毕竟我跑过图了emmmm)。
2：使用前清理了部分怪物不会影响，达到点位识别不到怪物会继续去下一个点位，（约等待30s）。
3：巡视怪都是走到路线中央，就算打不到也会在点位等待约30s，所以巡视怪也肯定会看到并打遭遇战。

**Comment by fatinghenji** [comment]
> 路线是从b站视频找的

可以提供下视频吗？感谢

**Comment by Starry-Wind** [comment]
https://b23.tv/v9zihko

不支持暂后台挂机，需要游戏窗口置顶（注意游戏分辨率）

**Comment by fatinghenji** [comment]
好的，感谢解答
