### ISSUE TITLE
关于沿用自动战斗设定这一设置

### ISSUE THREAD

**Issue by GamerNoTitle** [Starry-Wind/Honkai-Star-Rail#11]
在我实际使用中发现，如果游戏开了沿用自动战斗这一设置的话，在脚本运行的过程中，脚本点击自动按钮的这一操作会把自动战斗给关掉，是不是应该考虑加入一个自动战斗是否开启的判断呢？而不是什么情况都点一下这样的

**Comment by snowly233** [comment]
config.json 下面有相关设定，开沿用就1没有就0
