### ISSUE TITLE
 不知道如何开启

### ISSUE THREAD

**Issue by 013A** [Starry-Wind/Honkai-Star-Rail#13]
python安装好了，安装依赖也好了，就是不知道在哪用管理员开启

![未命名](https://user-images.githubusercontent.com/132829623/236681986-d92bb828-145e-499e-bdbc-2f13c90ccc8d.png)

**Comment by Starry-Wind** [comment]
用管理员打开cmd，cd进入你当前的文件夹，然后python 'Honkai Star Rail'

**Comment by Starry-Wind** [comment]
第一次使用请先运行get_width.py文件，指令应该是python3 ‘*****’。用tap补全代码

**Comment by 013A** [comment]
已经使用管理员开启了，执行后仍无反应
![image](https://user-images.githubusercontent.com/132829623/236685408-98ce8192-5dd1-425c-844b-ba2c5160d8f9.png)
![image](https://user-images.githubusercontent.com/132829623/236685730-e3ea93f2-1c2e-4245-992c-3919531ecc20.png)

**Comment by Starry-Wind** [comment]
请问一下你使用的文本语言是否为简体中文，当前识图仅支持简体中文，你可以把文本语言换成简体中文再运行

**Comment by 013A** [comment]
文本改为简中了，但只能运行到开启地图
![image](https://user-images.githubusercontent.com/132829623/236816401-398db154-58fb-4ee8-bab5-5844bb3cfaba.png)

**Comment by Starry-Wind** [comment]
如果你的电脑分辨率为2560*1440，请将游戏分辨率请调为1920*1080 （窗口化） ；如果你的电脑分辨率为1920*1080，请将游戏分辨率调为1920*1080（全屏幕）。也有可能是因为你没有使用管理员权限运行，或者是依赖没装齐。不过开始运行的时候人物不要在基座舱段启动脚本。应该是没有问题的，毕竟国服和国际服的图都是一样的

**Comment by 013A** [comment]
解决了,是分辨率的问题,萤幕原始设置是1600x900,改为1920x1080后就能正常执行了
