### ISSUE TITLE
[功能请求] 按键自定义、时间戳等

### ISSUE THREAD

**Issue by nyano** [Starry-Wind/Honkai-Star-Rail#158]
### 原因

按键
BUG
时间戳

### 功能简述

`                        pyautogui.keyDown("m")
                        pyautogui.keyUp("m")`

需求1：大大好。以前我是自己改map.py里自定义地图的按键的，但是因为现在加了自动更新和判断，造成没法自己改了
是否可以将打开地图的按键加入到config.json中，以便自定义地图按键？
需求2：初始阶段，config验证阶段，字卡在一起了，未知原因造成。config验证完成后续的正常
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/5079651/f92c6512-dd0f-43a6-973c-3c696624b6e5)
需求3：是否可以在开始和结束加个时间戳，最后加一个总计用时？

### 功能逻辑

按键
BUG
时间戳

**Comment by nyano** [comment]
环境：4k显示器 150% DPI  游戏以1080p窗口化运行
已测试BUG2 并非显示器DPI造成。

**Comment by Night-stars-1** [comment]
> 环境：4k显示器 150% DPI 游戏以1080p窗口化运行 已测试BUG2 并非显示器DPI造成。

bug2为bat文件问题，使用win的终端运行无该问题

**Comment by Night-stars-1** [comment]
按键已经添加，时间戳具体指哪里

**Comment by nyano** [comment]
时间戳指的是开始时的开始时间以及脚本最后结束时给个结束时间，以及整个脚本执行计算的整个完成时间
我看脚本上是没有时间显示的，但是在logs里看到了时间戳
其实我就想看看无干预整个脚本执行要多久，发现要2小时 滑稽

**Comment by Night-stars-1** [comment]
> 时间戳指的是开始时的开始时间以及脚本最后结束时给个结束时间，以及整个脚本执行计算的整个完成时间 我看脚本上是没有时间显示的，但是在logs里看到了时间戳 其实我就想看看无干预整个脚本执行要多久，发现要2小时 滑稽

是的要很久，脚本目前识图和等待不够好，我们正在改善，事实上跑完全程本来就需要很久
