### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HorenZ** [Starry-Wind/Honkai-Star-Rail#163]
### 问题描述

您好
我在运行的时候遇到了错误
NameError: name 'read_json_file' is not defined

### 预期行为

正常运行

### 实际行为

抛出异常：
NameError: name 'read_json_file' is not defined

### 截图或录屏

![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/32692196/1b218a52-1309-4a40-9353-b6aa2eb80d6b)

### 自动锄大地脚本版本

20230514004212

### 星穹铁道区服

国服

### 日志

日志文件为空

**Comment by Night-stars-1** [comment]
https://github.com/Starry-Wind/Honkai-Star-Rail/releases/tag/v1.1.0
