### ISSUE TITLE
[Bug] 2-6和2-7跳传送点失败

### ISSUE THREAD

**Issue by FlashIvano** [Starry-Wind/Honkai-Star-Rail#168]
### 问题描述

在地图界面卡住

### 预期行为

选择传送点，跳过去

### 实际行为

卡住

### 自动锄大地脚本版本

1.1.0

### 星穹铁道区服

国服

### 日志

[日志文件.log](https://github.com/Starry-Wind/Honkai-Star-Rail/files/11471054/default.log)

**Comment by snowly233** [comment]
你这是运行中推送了更新，更新最新版1.1.0再重新运行就行

**Comment by Night-stars-1** [comment]
应该是按钮点击无效

**Comment by Night-stars-1** [comment]
已经更换点击函数
https://github.com/Starry-Wind/Honkai-Star-Rail/blob/4ff5a0593fdfebdf3153f489f8ed183913b810be/tools/calculated.py#L36
