### ISSUE TITLE
[Bug] 点击自动战斗又是会点到右边的暂停

### ISSUE THREAD

**Issue by FlashIvano** [Starry-Wind/Honkai-Star-Rail#169]
### 问题描述

进暂停

### 预期行为

点击自动战斗

### 实际行为

进暂停

### 自动锄大地脚本版本

1.1.0

### 星穹铁道区服

国服

### 日志

[日志文件.log](https://github.com/Starry-Wind/Honkai-Star-Rail/files/11471056/default.log)

**Comment by apple050620312** [comment]
請開啟沿用自動戰鬥選項

**Comment by Night-stars-1** [comment]
https://github.com/Starry-Wind/Honkai-Star-Rail/blob/67c97b00d6fe2930c27d59d6b8f89dd9dbd5552d/config.json#L3
将改行改为1
