### ISSUE TITLE
[路线错误] 多个地图路线

### ISSUE THREAD

**Issue by nyano** [Starry-Wind/Honkai-Star-Rail#171]
### 问题描述

以下问题经过2-3天测试，属于多次出现的路线问题，单次出现的问题未包含
测试环境：4k显示器150DPI，游戏 1080P窗口化，分别在30帧和60帧环境下测试 跑图角色：艾丝妲
额外的建议：如果单批次怪物如果存在多个在一起的情况，当触发攻击完成后，能够多一次叠加攻击来减少可能漏怪不同时进入攻击状态的情况
脚本运行时间：1小时45分钟

收容舱段正下方的怪未到达，在前面一个怪有2次打击，但没有执行路线而直接结束了
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/5079651/a3347492-0330-41ec-90a7-1617bc66d100)

边缘通路第一段有一段无意义的行走路线，未知用途，也没怪
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/5079651/91f16a0d-a091-4b6e-9606-796912c69aae)

残响回廊最下方怪物由于行动路线较大，未达到【没注意是否有路线】
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/5079651/eedd2ccd-bb70-4cdb-b4d8-093c6c7cd819)
zhongbu中部不知道为什么要走左侧的传送点，，明明中间就有传送点，路线第一个怪有概率卡门【只是概率，最近几次正常】
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/5079651/701760dc-10dc-4533-8c42-436b37b8ba03)

大矿区上方怪物无路线被遗漏
下方3个怪由于有一个怪是有走动的，有概率未纳入攻击【最近几次正常】
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/5079651/0417626c-ca2f-4c9d-8621-21ffc502122c)

机械部落右上方一个怪多次被遗漏
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/5079651/436ffccb-b827-4c78-832a-1417a7e144b2)

流云渡：未打怪【没注意是否有线路】
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/5079651/e7cea080-bf7a-4ce0-a08d-d7d2f4ebd603)

迴星港最上方三个怪由于2个在一起1个较为远离，可能存在漏怪情况【不同时进入攻击】
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/5079651/b72d0310-74e3-4dce-acc6-c44eae79b7a4)

太卜司的路线可能存在了多个未知意义的线路？
太卜司左上角怪物第一个卡墙后，后续所有流程全部在转圈圈，无法正常执行【群里正好看到别人一样卡墙的图】
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/5079651/116344f3-5db1-49de-a908-c0c01eb761cf)
![F8A1$U4_7KEGA))Z}Y`NRVM](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/5079651/071b34d9-8c7a-4ab6-8758-2afe46468dde)

太卜司右上方由于是地图从左边过来的，所以整个流程错误。太卜司下方区域的怪物路线全都正常
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/5079651/b5f1b252-27f7-4b8c-a9ca-0b4a1cd6ac87)
工造司右上方的怪物未打【怪物需等待】
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/5079651/09511efd-3240-4255-85c1-6fbfdbfee3ed)

### 是否使用三月七跑图

- [ ] 是
- [ ] 否

### 日志

日志过长，只能传附件了

[日志文件.log](https://github.com/Starry-Wind/Honkai-Star-Rail/files/11471131/default.log)

**Comment by snowly233** [comment]
仙舟已修复，空间站和雅利洛VI目前无人维护，可以自行编写路线修复该错误，详细看readme

**Comment by 5570748** [comment]
雅利洛VI已修复，空间站是录制时不知道那里还有怪，你可以自行编写路线修复该错误并上传，详细看readme
