### ISSUE TITLE
[Bug] 首次启动的讯息挤在一起

### ISSUE THREAD

**Issue by TomIsFat** [Starry-Wind/Honkai-Star-Rail#173]
### 问题描述

首次启动的讯息挤在一起

### 预期行为

字体应该清晰可见

### 实际行为

首次启动的讯息挤在一起

### 截图或录屏

![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/76768214/bd42ac3d-9af3-444b-86b9-0ec9a3e9dc4b)

已经有提交修复对应bug的pull，请通过一下：https://github.com/Starry-Wind/Honkai-Star-Rail/pull/154 https://github.com/Starry-Wind/Honkai-Star-Rail/pull/157

### 自动锄大地脚本版本

2.7_test

### 星穹铁道区服

国服

### 日志

日志文件为空

**Comment by Night-stars-1** [comment]
请不要使用bat文件运行脚本

**Comment by TomIsFat** [comment]
> 请不要使用bat文件运行脚本

请告知您的运行 *Honkai_Star_Rail.py* 的方式，我阅读readme后只知道使用bat文件一键启动这一种方式
