### ISSUE TITLE
[Bug] Honkai_Star_Rail.bat被删除

### ISSUE THREAD

**Issue by MooreFoss** [Starry-Wind/Honkai-Star-Rail#185]
### 问题描述

Honkai_Star_Rail.bat被删除

### 预期行为

Honkai_Star_Rail.bat存在于根目录

### 实际行为

Honkai_Star_Rail.bat并不存在于根目录

### 自动锄大地脚本版本

2.7

### 星穹铁道区服

国服

### 日志

无

**Comment by 5upernova-heng** [comment]
您好，这不是 bug，bat 是主动被删除的
这是因为 bat 会存在一些问题，比如在部分设备中文字会挤到一起：#173

现在为了使用脚本，您需要在命令行通过 python 启动。具体方法请查阅资料
