### ISSUE TITLE
[功能请求] 使用 pipreqs 生成 requirements.txt，而不是手动添加

### ISSUE THREAD

**Issue by 5upernova-heng** [Starry-Wind/Honkai-Star-Rail#190]
### 原因

使用指定版本号的 libraries 可以保证稳定的服务。
目前分发的每一份产品都是直接安装最新版的库，这可能导致一部分库在更新后，接口无法向下兼容。

### 功能简述

使用 [pipreqs](https://github.com/bndr/pipreqs) 生成 requirements.txt，而不是手动添加

### 功能逻辑

不改变交互逻辑

### 实现参考

```bash
pip install pipreqs
# 在仓库根目录下
pipreqs . --encoding=utf8 --force
```

> 此功能可以加入 action-bot

**Comment by Night-stars-1** [comment]
感谢提醒，已添加
