### ISSUE TITLE
[Bug] [资源文件更新]version.json校验失败, 程序退出

### ISSUE THREAD

**Issue by xeivu** [Starry-Wind/Honkai-Star-Rail#208]
### 问题描述

1.16 無覆盖 管理员CMD 指令启动Honkai_Star_Rail.py 报错

### 预期行为

無

### 实际行为

無

### 截图或录屏

![螢幕擷取畫面 2023-05-16 022115](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/133697094/a10b3ff5-f0cc-469b-a540-f57443d04ea5)

### 自动锄大地脚本版本

2.7_test

### 星穹铁道区服

国际服

### 日志

02:15:59 - INFO	| update_file.update_file:129 - 3.1 -  [资源文件更新]正在检查远程版本是否有更新...
02:15:59 - INFO	| update_file.update_file:147 - 3.1 -  [资源文件更新]获取远程版本成功: 20230515221447
02:15:59 - INFO	| update_file.update_file:152 - 3.1 -  [资源文件更新]本地版本与远程版本不符，开始更新资源文件->https://hub.fgit.ml/Starry-Wind/Honkai-Star-Rail/archive/refs/heads/beta-2.7_test.zip
02:16:01 - INFO	| update_file.update_file:156 - 3.1 -  [资源文件更新]下载更新包成功, 正在覆盖本地文件: 0 -> 20230515221447
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/ISSUE_TEMPLATE/
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/ISSUE_TEMPLATE/bug_report.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/ISSUE_TEMPLATE/bug_report_en.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/ISSUE_TEMPLATE/config.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/ISSUE_TEMPLATE/feature_request.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/ISSUE_TEMPLATE/feature_request_en.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/ISSUE_TEMPLATE/route_bug.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/ISSUE_TEMPLATE/route_bug_en.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/release.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/workflows/
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/workflows/auto-merge.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/workflows/codeql.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/workflows/dependency-review.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/workflows/pylint.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/workflows/update_map.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.github/workflows/upload-to-release.yml
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/.gitignore
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/Honkai_Star_Rail.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/LICENSE
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/README.md
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/README_CHT.md
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/get_width.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/map_res_list.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/requirements.txt
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/star_list.json
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/test.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/tools/
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/tools/calculated.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/tools/config.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/tools/exceptions.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/tools/get_angle.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/tools/log.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/tools/map.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/tools/record_v7.2.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/tools/requests.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/tools/switch_window.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/tools/update_file.py
02:16:01 - DEBUG	| update_file.unzip:49 - 3.1 -  [资源文件更新]正在提取Honkai-Star-Rail-beta-2.7_test/version.json
02:16:01 - INFO	| update_file.update_file:174 - 3.1 -  [资源文件更新]正在校验资源文件
02:16:02 - DEBUG	| update_file.verify_file_hash:38 - 3.1 -  6d37061c8d23967c0a1f98398f980d54
02:16:02 - DEBUG	| update_file.verify_file_hash:38 - 3.1 -  5c3ba1f9c631abd41644a4e77e7cb724
02:16:02 - DEBUG	| update_file.verify_file_hash:38 - 3.1 -  c9c656d8903253721e907c5053f83f77
02:16:02 - DEBUG	| update_file.verify_file_hash:38 - 3.1 -  a3113833169f0c95e5fb33d498bf5f53
02:16:02 - ERROR	| exceptions.__init__:19 - 3.1 -  [资源文件更新]version.json校验失败, 程序退出
02:16:02 - DEBUG	| exceptions.__init__:20 - 3.1 -  NoneType: None

02:16:02 - ERROR	| Honkai_Star_Rail.<module>:122 - 3.1 -  Traceback (most recent call last):
  File "E:\Honkai-Star-Rail-1.1.6\Honkai_Star_Rail.py", line 112, in <module>
    main()
  File "E:\Honkai-Star-Rail-1.1.6\Honkai_Star_Rail.py", line 20, in main
    up_data()
  File "E:\Honkai-Star-Rail-1.1.6\Honkai_Star_Rail.py", line 105, in up_data
    update_file_main(**up)
  File "E:\Honkai-Star-Rail-1.1.6\tools\update_file.py", line 262, in update_file_main
    check_file_status = asyncio.run(update_file(url_proxy,raw_proxy,False,skip_verify,type,version,url_zip,unzip_path,keep_folder,keep_file,zip_path,name))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XeIVU\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\Honkai-Star-Rail-1.1.6\tools\update_file.py", line 190, in update_file
    raise Exception(f"[资源文件更新]{path}校验失败, 程序退出")
tools.exceptions.Exception: [资源文件更新]version.json校验失败, 程序退出

**Comment by YourGodTao** [comment]
我遇到了同样的问题，我的做法是把update_file.py文件中的verify_file_hash函数全部返回True，这样就可以愉快的继续使用了~

**Comment by xeivu** [comment]
问题解决,感谢

**Comment by Night-stars-1** [comment]
以修复
另外关闭更新请修改script_debug为true
