### ISSUE TITLE
[功能请求] 将游戏加载地图期间的固定5秒Sleep改为识别黑幕过场动画是否结束

### ISSUE THREAD

**Issue by weiduhuo** [Starry-Wind/Honkai-Star-Rail#216]
### 原因

使用脚本期间多次发现进入新地图后自动寻路失败，发现是因为地图加载时长大于预设的固定5秒时长，导致"map"序列的开头部分操作失效，致使后序寻路失败。

### 功能简述

修改[tools/map.py/auto_map 此处的代码](https://github.com/Starry-Wind/Honkai-Star-Rail/blob/fd75baaeb6f93472783c9665fb571bbe3edd9707/tools/map.py#LL57C27-L57C27)
将游戏加载地图期间的固定5秒Sleep改为识别黑幕过场动画是否结束，增强脚本对低配电脑的泛用性。

### 功能逻辑

将游戏加载地图期间的固定5秒Sleep改为识别黑幕过场动画是否结束

### 实现参考

...
time.sleep(3)
while is_black_field():   # 截图识别指定区域是否为黑场
...time.sleep(1)
...

**Comment by Xe-No** [comment]
已实现

**Comment by Xe-No** [comment]
我的旧电脑终于也可以跑了ww

**Comment by weiduhuo** [comment]
> ### 原因
> 使用脚本期间多次发现进入新地图后自动寻路失败，发现是因为地图加载时长大于预设的固定5秒时长，导致"map"序列的开头部分操作失效，致使后序寻路失败。
> 
> ### 功能简述
> 修改[tools/map.py/auto_map 此处的代码](https://github.com/Starry-Wind/Honkai-Star-Rail/blob/fd75baaeb6f93472783c9665fb571bbe3edd9707/tools/map.py#LL57C27-L57C27) 将游戏加载地图期间的固定5秒Sleep改为识别黑幕过场动画是否结束，增强脚本对低配电脑的泛用性。
> 
> ### 功能逻辑
> 将游戏加载地图期间的固定5秒Sleep改为识别黑幕过场动画是否结束
> 
> ### 实现参考
> ... time.sleep(3) while is_black_field(): # 截图识别指定区域是否为黑场 ...time.sleep(1) ...

**Comment by htshts1115** [comment]
在最新修改后，我还是遇到了超时问题，发现是因为判断黑幕函数的阈值设置太低，没有进入while循环导致。可能不同屏幕显示不同？
修改阈值为45-50即可，或者在判断黑幕后再增加sleep
