### ISSUE TITLE
[Bug] 起始题图问题

### ISSUE THREAD

**Issue by Seazer-x** [Starry-Wind/Honkai-Star-Rail#224]
### 问题描述

请输入起始地图（如果从头开始请输入0）应该输入什么格式的字符？

### 预期行为

起始运行指定地图的脚本

### 实际行为

Honkai_Star_Rail.main:34 - 3.1 - 错误编号

### 截图或录屏

![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/62045004/f0351dae-9e95-44c4-bfe6-2d6746e7b179)

![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/62045004/da09423b-fd08-42cf-8042-f3f9f247485e)

### 自动锄大地脚本版本

beta-2.7_test

### 星穹铁道区服

国服

### 日志

[日志文件.2023-05-18_00-31-10_722586.log](https://github.com/Starry-Wind/Honkai-Star-Rail/files/11503603/2023-05-18_00-31-10_722586.log)

**Comment by Klamist** [comment]
是“3-2_3”
打开你的map文件夹，里面有一堆的文件。那些就是了。

**Comment by Seazer-x** [comment]
好的，感谢
