### ISSUE TITLE
[Bug] NameError: name 'Map' is not defined. Did you mean: 'map'?

### ISSUE THREAD

**Issue by ZouloveGhack** [Starry-Wind/Honkai-Star-Rail#230]
### Problem Description

我在Honkai-Star-Rail-latest打开CMD 并使用py Honkai_Star_Rail.py 过后就出现[Bug] NameError: name 'Map' is not defined. Did you mean: 'map'? 这个问题 。如果我把Honkai_Star_Rail.py文件改成.bat文件会出现不是内部或外部命令，也不是可运行的程序
或批处理文件。

### expected behavior

应该发生
8：如果你不知道地图编号是什么，或者你想要重新开始跑图，输入"0"后回车

9：在等候开始五秒期间，请点返回游戏画面，确保没有开启任何菜单及界面，等候程序运行

### actual behavior

因为我看到 7：开启Honkai_Star_Rail.bat等候程序自动运行至可输入地图编辑处，可以打开但是并没有只看到.py 所以就用cmd打开但是却出现了NameError: name 'Map' is not defined. Did you mean: 'map'? 这个问题 

### screenshot or screen recording

![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/28489226/e2274239-5c00-4f3c-92ef-b0e95d031131)
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/28489226/008dc648-2529-4b3a-8de4-9c1ce385e964)

### Honkai-Star-Rail version

1.0.5/latest

### Honkai Star Server

Global

### log

我对代码不是很熟也不知道怎么启动就想了这两个办法我还以为有.bat文件可以一键启动但是没有心累（；´д｀）ゞ
想说可以放开手脚刷怪了/_ \

**Comment by ZouloveGhack** [comment]
我找到绝决方法了你们就不可以把bat文件放在你们自己的文件夹吗幸好我找到制作bat文件的作者并复制代码自己绝决了😂😅

**Comment by LiberatorHg** [comment]
怎么解决map报错的呀 我也是一键bat启动 看了下代码 调用的tool.map 按理应该没毛病才对
