### ISSUE TITLE
[功能请求] 更详细的使用指南，或者一个视频

### ISSUE THREAD

**Issue by esdrtf** [Starry-Wind/Honkai-Star-Rail#239]
### 原因

如图，按照步骤做了但是honkaistarrail那个文件打开了没反应，不知道是哪里错了

### 功能简述

更详细的步骤或者视频更好

### 功能逻辑

如图，按照步骤做了但是honkaistarrail那个文件打开了没反应，不知道是哪里错了

**Comment by ZouloveGhack** [comment]
如果你没有看到.bat文件那么就是没有下载，请到这个网站下载.bat文件并转移道你最新的文件
https://github.com/apple050620312/Honkai-Star-Rail_bat/blob/main/Honkai_Star_Rail.bat
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/28489226/7a0f1149-99ee-4bf2-9f3b-b4c4cfcdb6b2)

**Comment by esdrtf** [comment]
谢啦
但是那个运行了然后
![屏幕截图(1)](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/77639813/1a1e1186-d9ce-451b-a9f1-2895d0afa0e3)

**Comment by esdrtf** [comment]
莫名其妙就搞好了，谢谢大佬的发电和帮助！
