### ISSUE TITLE
[Bug] NameError: name 'switch_window' is not defined

### ISSUE THREAD

**Issue by ZouloveGhack** [Starry-Wind/Honkai-Star-Rail#241]
### 问题描述

当我更新地图包后就出现这个问题

NameError: name 'switch_window' is not defined

'pip' is not recognized as an internal or external command,
operable program or batch file.
### 预期行为

跑图

### 实际行为

更新最新后就将了

### 截图或录屏

![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/28489226/7589d2e6-2d8f-4687-b51a-c1fcc2f80d5d)
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/28489226/a48a156b-ee1d-4f1a-a50b-0e70fcccff2e)

### 自动锄大地脚本版本

latest

### 星穹铁道区服

国际服

### 日志

[日志文件.log](https://github.com/Starry-Wind/Honkai-Star-Rail/files/11522403/default.log)

**Comment by Starry-Wind** [comment]
已经回退版本，可正常使用

**Comment by ZouloveGhack** [comment]
> 已经回退版本，可正常使用
谢了
