### ISSUE TITLE
[Bug] 無法正常更新使用

### ISSUE THREAD

**Issue by d170798091** [Starry-Wind/Honkai-Star-Rail#245]
### 问题描述

![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/134176008/120d9fab-7861-4137-8700-ace5dfe328bd)
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/134176008/0eeb286f-b048-4472-a021-59fc08d6b48d)

### 预期行为

應該能順利執行

### 实际行为

上一個更新前還能用,稍早更新的時候就不能使用

### 自动锄大地脚本版本

Honkai-Star-Rail-1.1.7

### 星穹铁道区服

国际服

### 日志

![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/134176008/120d9fab-7861-4137-8700-ace5dfe328bd)
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/134176008/0eeb286f-b048-4472-a021-59fc08d6b48d)

**Comment by esdrtf** [comment]
+1, 我还以为是就我的问题

**Comment by skycon8** [comment]
+1.  更新了用不了

**Comment by FeirBlox** [comment]
直接把校验部分先注释了就行了

**Comment by esdrtf** [comment]
修好了，大佬们真效率
