### ISSUE TITLE
[路线错误] 3-3_4第59步f键入画不成功

### ISSUE THREAD

**Issue by kz-wind** [Starry-Wind/Honkai-Star-Rail#247]
### 问题描述

3-3_4第59步f键入画不成功，且没有未增加动画等待时间

### 是否使用三月七跑图

- [ ] 是
- [X] 否

### 日志

12:28:59 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:49/135 {'w': 2.8916614055633545}
12:29:02 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:50/135 {'s': 1.6314735412597656}
12:29:03 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:51/135 {'a': 0.6979209899902344}
12:29:04 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:52/135 {'w': 2.1355526447296143}
12:29:06 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:53/135 {'d': 0.874366283416748}
12:29:07 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:54/135 {'d': 1.383190393447876}
12:29:08 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:55/135 {'w': 3.1529858112335205}
12:29:12 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:56/135 {'a': 0.6193225383758545}
12:29:12 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:57/135 {'s': 0.819035530090332}
12:29:13 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:58/135 {'d': 0.6528077125549316}
12:29:14 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:59/135 {'f': 0.38869028091430663}
12:29:14 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:60/135 {'w': 6.500455379486084}
12:29:21 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:61/135 {'a': 1.5512307167053223}
12:29:22 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:62/135 {'w': 4.109583854675293}
12:29:26 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:63/135 {'s': 0.5974218845367432}
12:29:27 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:64/135 {'d': 1.5304452419281005}
12:29:28 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:65/135 {'w': 3.131971597671509}
12:29:32 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:66/135 {'a': 1.2176332473754883}
12:29:33 - INFO	| calculated.auto_map:158 - 3.1 -  执行map_3-3_4文件:67/135 {'w': 2.41235089302063}

**Comment by Night-stars-1** [comment]
路线中不应该存在入画

**Comment by kz-wind** [comment]
@Night-stars-1 59步的f键就是入画，否则它不应存在此处，然后游戏内截图如下，按脚本执行，59步左右确实在入画前卡墙了
![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/33864547/a8055240-9492-4182-8035-1223b450f688)
