### ISSUE TITLE
一个有关屏幕旋转的问题

### ISSUE THREAD

**Issue by lanyucrim** [Starry-Wind/Honkai-Star-Rail#3]
作者您好，我发现您关于self.win32api.mouse_event(self.win32con.MOUSEEVENTF_MOVE，x,0)就是鼠标滑动屏幕这一块在我电脑是无法转动正常角度的，例如第一个map里的self.win32api.mouse_event(self.win32con.MOUSEEVENTF_MOVE, 4650, 0)这个4650，我需要改成3100才能正常，想知道您这个参数是依据什么来定的，还有就是请问后续还会大改整个架构吗？

**Comment by Starry-Wind** [comment]
好的，我也发现了这个问题，因为有些时候加载确实会慢点，后面会改

**Comment by lanyucrim** [comment]
那请问那个旋转的参数您是如何取值的。

**Comment by lanyucrim** [comment]
因为我看到这个脚本去速学的有关函数（汗颜），有些参数不太明白。我测试下来基本每一个旋转都需要我进行额外修改

**Comment by Starry-Wind** [comment]
其实就是自己慢慢转测试出来的，但是我不太确定每个用户是不是真的要旋转这么多。。。

**Comment by lanyucrim** [comment]
OK，谢谢，那就等您后续的更新了哈哈，等到主体框架稳定我就去修改参数，辛苦啦

**Comment by Starry-Wind** [comment]
因为我试了其他库，大部分都会把镜头鼠标移动会屏蔽掉，所以用了win32，如果有更好的解决可以说说 qwq

**Comment by Starry-Wind** [comment]
我也是刚开始学Java后端，然后玩python试了一下这些图形脚本，然后慢慢开始搞一下这些图形脚本的，所以很多东西都不太会。。。

**Comment by lanyucrim** [comment]
哈哈哈，那我可以当你的测试（狗头

**Comment by Starry-Wind** [comment]
分辨率不一样，旋转就会有误差

**Comment by lanyucrim** [comment]
哈哈哈，辛苦了，原来是分辨率的问题

**Comment by lanyucrim** [comment]
那这个只要统一规范就行了，影响不大，明天我再去看看还有木有bug，今天怪都被我刷了

**Comment by Starry-Wind** [comment]
问题就来了，不同用户自带的屏幕分辨率不一样，虽然游戏分辨率使用一样，但是旋转的方向会有误差，这就难搞了

**Comment by lanyucrim** [comment]
那有没有获取屏幕分辨率的工具，然后再去设定不同的值

**Comment by lanyucrim** [comment]
不过我觉得假如做多人使用最好还是依照1080p，因为大部分人的分辨率应该都是这个

**Comment by lanyucrim** [comment]
2k和4k以及1080p中间可能存在一些关系，乘于一个系数，就比如你的我需要手动乘于3分之2就可以正常使用

**Comment by lanyucrim** [comment]
当然屏幕旋转我只测试了第一和第二个，第三个没去试，明天去看看

**Comment by Starry-Wind** [comment]
嗯
