### ISSUE TITLE
地图探索寻路模块局限性会不会太大了？

### ISSUE THREAD

**Issue by Alone749-i** [Starry-Wind/Honkai-Star-Rail#6]
作者上午好，非常感谢开源该项目供大伙一块方便解放双手。
阅读了项目代码，感觉寻路模块会不会局限性太大了。必须得控制好地图，每一条路径都要一个个写感觉后期扩展起来不是很方便。
特别是对于模拟宇宙这种地图还会改变的，就很难处理了。不知道作者有没有更好的想法改善该部分模块，非常愿意一同维护完善。

**Comment by Starry-Wind** [comment]
是的，这个寻路我的技术力不太够所有只能想到这种最简单的方法，对于模拟宇宙因为地图在地图池随机抽选的所以写寻路也很麻烦，现在我也挺想知道还没有其他方法能实现寻路模块 qwq

**Comment by Alone749-i** [comment]
非常感谢大佬的代码，我也去找找相关思路一起交流完善。

**Comment by Night-stars-1** [comment]
> 是的，这个寻路我的技术力不太够所有只能想到这种最简单的方法，对于模拟宇宙因为地图在地图池随机抽选的所以写寻路也很麻烦，现在我也挺想知道还没有其他方法能实现寻路模块 qwq

您好，可否开一个QQ或者tg群聊方便一起交流或者用户反馈bug

**Comment by Alone749-i** [comment]
> > 是的，这条路我的技术力不够所有只能想到这种最简单的方法，对模拟宇宙因地图在地图池随机抽取的所以写寻路也很烦，现在我也坚持想知道还没有其他方法能实现现寻路模块qwq
> 
> 您好，可否开一个QQ或tg群聊方方便一起交流或使用用户反喷bug

+1

**Comment by Starry-Wind** [comment]
好的，今晚我去开个群，现在我得先去补个觉，下午还有点事，qwq

**Comment by Starry-Wind** [comment]
qq群：719540466 欢迎加入

**Comment by apple050620312** [comment]
我這邊用不了QQ，能不能開個TG群啊，因為我沒有中國手機號

**Comment by foodtooth** [comment]
开个slack可以大家都用

**Comment by apple050620312** [comment]
@Starry-Wind 抱歉mention，可以考慮創除了QQ以外的討論區嗎，我也想參與這個專案的討論
