### ISSUE TITLE
[路线错误] 

### ISSUE THREAD

**Issue by SouthlivingCHINA** [Starry-Wind/Honkai-Star-Rail#69]
### 问题描述

bug1 （其实不算bug）目前在小关内的几次传送不是切到星轨航图再进入小图传送，而是加快速度直接小图内几次传送的话，实际上假设我人在别的图，那么我不能从中间开始，他读取不到那张图，例如只能从1-2_1开始，而不能从1-2_2开始。
bug2 1-2_2 第一个怪结束，到二个怪路途中卡墙
bug3 1-2_4 走不到怪，卡墙
bug4 2-1_2 不是每次都卡，但有概率卡在第一个怪前，还没走到第一个怪的一根断木
bug5 2-2_1 卡在铁门
后面bug太多了整理不完 先这么点吧
这些bug我都反复几遍测试了 确认是bug而非偶然事件，根据bug4我发现，每次从传送点出来的转动可能都有些许误差，因为他不是每次都卡住，有时候不卡住。猜测可能的解决方案是每次转动输入之间可以设置一两百毫秒延迟，然后每次转动幅度不要太大。
![1-2_2](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/133109004/ceca9c2f-0cd4-4670-ad68-f670056e8dce)
![2-1_2](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/133109004/631fdd57-7071-45b0-a4ec-08f332c8bf24)
![1-2_2（1）](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/133109004/b61baeaf-b394-45ec-b69c-bd6f133c5099)

![1-2_4](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/133109004/74b38cba-eb8d-4f52-ad57-6ecb3a677923)
![2-2_1](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/133109004/1951f817-4254-440e-875c-5d4dafdca2bb)

### 是否使用三月七跑图

- [X] 是
- [ ] 否

### 日志

日志是正常的，因为他就是没走到怪上，如果我人工干预让他走到怪上，脚本可以正常进行下去。

**Comment by Night-stars-1** [comment]
好的，感谢反馈，后续会处理的

**Comment by Starry-Wind** [comment]
旋转视角的话，摄像机位置可能不太稳定，而且不同设备可能由于帧数或其他奇奇怪怪的原因会导致有误差，旋转越多可能导致误差逐渐累计变大导致后面路线有问题

**Comment by apple050620312** [comment]
不旋轉視角純WASD的話有可能比較好嗎

**Comment by Starry-Wind** [comment]
是的，昨天晚上有人录制的3-1不旋转视角都是可以正常使用的

**Comment by Night-stars-1** [comment]
> 不旋轉視角純WASD的話有可能比較好嗎

会，目前转视角是直接转过去的，没有设置延迟，我准备设置点延迟，一点一点转

**Comment by apple050620312** [comment]
轉視角轉太快有時候畫面卡了一下角度就偏掉了

**Comment by Night-stars-1** [comment]
跑了一遍，没有再出现路线异常了
