### ISSUE TITLE
请教一下是怎么方便的一键以管理员权限运行的

### ISSUE THREAD

**Issue by TomIsFat** [Starry-Wind/Honkai-Star-Rail#7]
使用bat文件，写入以下命令，点击一键启动，无法以管理员权限运行：
`start cmd /k conda activate starrail && python "Honkai Star Rail.py"`

**Comment by apple050620312** [comment]
我寫了個代碼放到PR了 看看大佬們要不要幫我merge

**Comment by apple050620312** [comment]
@TomIsFat @lanqianlv 新增了一個exe檔 直接點那個就能以管理員權限開啟了
