### ISSUE TITLE
下载启动后依赖自检通过，但是脚本不能运行[Bug] 

### ISSUE THREAD

**Issue by Emagelle** [Starry-Wind/Honkai-Star-Rail#71]
### 问题描述

下载2.7的包后运行管理员运行EXE文件，依赖安装检查挺顺利的，后来就显示“读取资源列表失败，请尝试更换github资源地址”

### 预期行为

不清楚，没有成功运行过。

### 实际行为

输入地图编号0之后切回游戏页面无反应，等待后返回看LOG
见Log

### 自动锄大地脚本版本

2.7

### 星穹铁道区服

国服

### 日志

10:57:07 - WARNING	| config.check_file:84 - 2.8 -  读取资源列表失败，请尝试更换github资源地址
10:57:09 - INFO	| main.main:16 - 2.8 -  脚本将于5秒后运行,请确保你的游戏置顶
10:57:14 - INFO	| get_width.get_width:14 - 2.8 -  461612
10:57:14 - INFO	| get_width.get_width:16 - 2.8 -  崩坏：星穹铁道
10:57:14 - INFO	| get_width.get_width:38 - 2.8 -  Real resolution: 1920 x 1080
10:57:14 - INFO	| main.main:21 - 2.8 -  开始运行，请勿移动鼠标和键盘
10:57:14 - INFO	| main.main:22 - 2.8 -  若脚本运行无反应,请使用管理员权限运行
10:57:14 - INFO	| map.auto_map:58 - 2.8 -  错误编号
10:57:14 - INFO	| main.main:27 - 2.8 -  脚本已经完成运行

**Comment by Starry-Wind** [comment]
你地图资源可能没下载，挂梯子重新试试？

**Comment by Night-stars-1** [comment]
10:57:07 - WARNING | config.check_file:84 - 2.8 - 读取资源列表失败，请尝试更换github资源地址
https://github.com/Starry-Wind/Honkai-Star-Rail/blob/e2f06d15ca6a31c3a68e59383667d9e10c766350/main.py#L11
删除https://ghproxy.com/或者更换其他代理

**Comment by Emagelle** [comment]
谢谢大佬指点，应该是代理冲突了，我把CLASH的全局代理关了就可以了
