### ISSUE TITLE
[Bug] No module named 'get_width'

### ISSUE THREAD

**Issue by laobinggan** [Starry-Wind/Honkai-Star-Rail#89]
### 问题描述

正在自動更新地圖檔
无法获取组件
Traceback (most recent call last):
  File "C:\work\py\Honkai-Star-Rail\main.py", line 1, in <module>
    from get_width import get_width
ModuleNotFoundError: No module named 'get_width'

### 预期行为

获取

### 实际行为

呼叫偶去

### 截图或录屏

![QQ截图20230511211803](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/56704330/c9edcaed-0058-445c-a0dc-5493ac276c20)

### 自动锄大地脚本版本

2.7

### 星穹铁道区服

国服

### 日志

![image](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/56704330/a8bf8599-82a3-4a3e-b047-fd5454383388)

**Comment by xuan06zyx** [comment]
有安装好脚本文件吗?全都在一个目录下吗?是怎么安装的呢?

**Comment by Night-stars-1** [comment]
确实文件，重新下载项目
