### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by NakanoSanku** [Starry-Wind/Honkai-Star-Rail#9]
- 首先pillow库没在requirement中，会导致报错
- 其次容错率太低了，很容易使用不了，(例如部分怪已经清了无法判断，导致卡住
- 后期还是建议加入后台键鼠和截图的方案，毕竟挂机嘛前台可以做别的事，同时也能减少脚本出错的概率（参考大漠？
- 自动寻路其实我也没啥太好的建议（没有涉猎这方面，感觉还是动内存比较好实现
- 如果可以的话适当增加一些方便调试的悬浮提示同时也方便用户知道目前脚本进度
- 最后还是感谢开源，希望项目越来越好（毕竟图色脚本基本不抓

**Comment by Starry-Wind** [comment]
第一点等会更改。第二点怪清了其实会原地等待约40s（同时避免没开到巡逻怪），等完后还会继续移动。第三点本来开始是想用句柄抓程序来实现的，但是技术力不行捏qwq，后面看看有没有办法实现。第四点关于自动寻路，目前阶段打算手动录入路线来实现，毕竟怪物是固定点位，如果动内存的话有反作弊肯定寄，所以不能动内存。第五点后续继续完善提示的。感谢issue

**Comment by Umegiri** [comment]
requirement是不是还少了个pynput

**Comment by apple050620312** [comment]
pynput最近我補上了
