### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by asdasdwetr** [Starry-Wind/Honkai-Star-Rail#91]
### 问题描述

执行脚本后，无法正常获取github上的地图json资源

### 预期行为

能够正常下载github上的地图json资源

### 实际行为

下载速度过于缓慢

### 截图或录屏

![3UI}84{S8$ZG`JD5F0 PFKS](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/128452281/76e8bf03-ea06-426c-819d-e34ed6094566)
![EWQHZJ O4PW{_C6F89TC3D2](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/128452281/80a4c1e8-d1fc-45b5-9958-d73044aee3f7)

### 自动锄大地脚本版本

2.7_test v1.0.0

### 星穹铁道区服

国服

### 日志

[日志文件.log](https://github.com/Starry-Wind/Honkai-Star-Rail/files/11453548/default.log)

**Comment by Night-stars-1** [comment]
下载速度取决于你的网络环境
