### ISSUE TITLE
[Feature] 地图编号格式？

### ISSUE THREAD

**Issue by michael-pptf** [Starry-Wind/Honkai-Star-Rail#93]
### 原因

地图编号格式是否可以列一个表格？这样如果中途遇到问题，可以从某一个地图重新开始。

### 功能简述

地图编号对应的地图与区块表格

### 功能逻辑

直接列出需要输入的地图编号，如1-1代表黑塔空间站的收容舱段起点#1，1-2代表黑塔空间站，收容舱段起点#2.

### 实现参考

目前地图编号的输入格式在README中并未明确。在README中，作者指出输入0为最开始的路径点。那么，如果我想要去黑塔空间站的支援舱段，该输入什么呢？是3，是4，还是1-4？

**Comment by apple050620312** [comment]
黑塔空间站的支援舱段是1-3_1

**Comment by xuan06zyx** [comment]
https://www.wolai.com/6BTbLT52v3y7P9XZ5YTjQd

**Comment by xuan06zyx** [comment]
> ### 原因
> 地图编号格式是否可以列一个表格？这样如果中途遇到问题，可以从某一个地图重新开始。
> 
> ### 功能简述
> 地图编号对应的地图与区块表格
> 
> ### 功能逻辑
> 直接列出需要输入的地图编号，如1-1代表黑塔空间站的收容舱段起点#1，1-2代表黑塔空间站，收容舱段起点#2.
> 
> ### 实现参考
> 目前地图编号的输入格式在README中并未明确。在README中，作者指出输入0为最开始的路径点。那么，如果我想要去黑塔空间站的支援舱段，该输入什么呢？是3，是4，还是1-4？

我想你可能需要这个https://www.wolai.com/6BTbLT52v3y7P9XZ5YTjQd

**Comment by Night-stars-1** [comment]
> * `name`为地图名称
>   * 编写方式为 星球代号-地图代号_文件序号
>   * 星球代号: 空间站:1|雅利洛:2|仙舟:3
>   * 地图和文件代号: 按数序来
